export const BARANGAYS = [
  "Agno",
  "Amistad",
  "Barangobong",
  "C. Lichauco",
  "Carriedo",
  "Evangelista",
  "Guzon",
  "Lawak",
  "Legaspi",
  "Libertad",
  "Magallanes",
  "Panganiban",
  "Poblacion A",
  "Poblacion B",
  "Poblacion C",
  "Poblacion D",
  "Saleng",
  "Santo Domingo",
  "Toketec",
  "Trenchera",
  "Zamora",
] as const
