import type { Metadata } from "next";
import { Figtree } from 'next/font/google';
import "./globals.css";
import NextAuthProvider from "@/components/providers/next-auth-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Header from "@/components/sections/Header";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "./providers/query-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/sections/Footer";

const figtree = Figtree({
  subsets: ['latin'],
  weight: [ '300', '400', '500', '700', '800'],
  variable: "--font-figtree",
});


export const metadata: Metadata = {
  title: "Tayug Skills Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions)
    console.log(session);
  return (
    <html lang="en">
      <body
        className={` ${figtree.className} antialiased`}
      >
        <NextAuthProvider session={session}>
        <Header/>
          <QueryProvider>
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </QueryProvider>
        </NextAuthProvider>
        <Toaster position="top-right"/>
        <Footer/>
      </body>
    </html>
  );
}
