import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
/* import Header from "@/components/sections/Header"; */

const poppins = Poppins({
  subsets: ['latin'],
  weight: [ '300', '400', '500', '700', '800'],
  variable: "--font-poppins",
});


export const metadata: Metadata = {
  title: "Tayug Skills Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased`}
      >
        {/* <Header/> */}
        {children}
      </body>
    </html>
  );
}
